version: '3.8'

services:
  insight-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insight-fe
    image: insight-fe:latest
    ports:
      - "${INSIGHT_FE_PORT:-6500}:6500"
    environment:
      - NODE_ENV=
      - PORT=${INSIGHT_FE_PORT:-6500}
      - INSIGHT_FE_PORT=${INSIGHT_FE_PORT:-6500}
    restart: always
