version: '3.8'

services:
  insight-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insight-fe
    ports:
      - "${INSIGHT_FE_PORT:-6500}:6500"
    environment:
      - NODE_ENV=production
      - INSIGHT_FE_PORT=${INSIGHT_FE_PORT:-6500}
    networks:
      - insight-fe-net
    restart: always

networks:
  insight-fe-net:
    driver: bridge
